### ISSUE TITLE
Add support for extended field type: 10 (INO_EXT_TYPE_DIR_STATS_KEY)

### ISSUE THREAD

**Issue by prats84** [libyal/libfsapfs#42]
While using image_export.py to extract data from a VMDK file. The VMDK is from  MacOS Catalina and APFS partitioned. The inode `12884932415` points to`~/Library/Application Support/CloudDocs folder.`

The CloudDocs folder is related to iCloud Drive. 

* Version 
```
image_export.py -V
plaso - image_export version 20210606
````

* Error 
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/image_export.py", line 92, in <module>
    if not Main():
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/image_export.py", line 62, in Main
    tool.ProcessSources()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/plaso/cli/image_export_tool.py", line 796, in ProcessSources
    self._Extract(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/plaso/cli/image_export_tool.py", line 342, in _Extract
    for path_spec in path_spec_generator:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/plaso/engine/extractors.py", line 544, in ExtractPathSpecs
    for extracted_path_spec in self._ExtractPathSpecs(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/plaso/engine/extractors.py", line 390, in _ExtractPathSpecs
    for extracted_path_spec in self._ExtractPathSpecsFromFileSystem(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/plaso/engine/extractors.py", line 509, in _ExtractPathSpecsFromFileSystem
    for extracted_path_spec in searcher.Find(find_specs=find_specs):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/dfvfs/helpers/file_system_searcher.py", line 588, in Find
    for matching_path_spec in self._FindInFileEntry(file_entry, find_specs, 0):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/dfvfs/helpers/file_system_searcher.py", line 562, in _FindInFileEntry
    for matching_path_spec in self._FindInFileEntry(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/dfvfs/helpers/file_system_searcher.py", line 562, in _FindInFileEntry
    for matching_path_spec in self._FindInFileEntry(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/dfvfs/helpers/file_system_searcher.py", line 562, in _FindInFileEntry
    for matching_path_spec in self._FindInFileEntry(
  [Previous line repeated 1 more time]
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/dfvfs/helpers/file_system_searcher.py", line 561, in _FindInFileEntry
    for sub_file_entry in file_entry.sub_file_entries:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/dfvfs/vfs/apfs_file_entry.py", line 145, in _GetSubFileEntries
    for path_spec in directory.entries:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/dfvfs/vfs/apfs_file_entry.py", line 32, in _EntriesGenerator
    for fsapfs_sub_file_entry in fsapfs_file_entry.sub_file_entries:
OSError: pyfsapfs_file_entry_get_sub_file_entry_by_index: unable to retrieve sub : 17. libfsapfs_inode_read_value_data: unsupported extended field type: 10. libfsapfs_file_system_btree_get_inode_by_identifier: unable to read inode value data. libfsapfs_file_entry_get_sub_file_entry_by_index: unable to retrieve inode: 12884932415 from file system B-tree.
```

**Comment by joachimmetz** [comment]
@prats84 thx for the report, `libfsapfs_inode_read_value_data: unsupported extended field type: 10` interesting find.

Per https://github.com/libyal/libfsapfs/blob/main/documentation/Apple%20File%20System%20(APFS).asciidoc#extended_field_types  extended field type 10 is `INO_EXT_TYPE_DIR_STATS_KEY`. 

"The CloudDocs folder is related to iCloud Drive." thx for this contextual hint. I'll need to take a closer look to see if I can create some test data with this format feature and implement support for it

**Comment by prats84** [comment]
Thanks for looking into this enhancement. Sorry, I don't have any test data that I can share.

Let me try and create a VM image with dummy data.

**Comment by joachimmetz** [comment]
Found an image with this format feature, and newer extended fields types. Changes to support this feature will be integrated in upcoming commits. Closing this issue.
